### PR TITLE
DP3 - Min Falling path

### PR DESCRIPTION
**Pull request by UmangThakur15**
Please review

### CODE REVIEW

**Comment by UmangThakur15** [comment]
Please Review- Min Falling path and Delete Earn Problem.

**Review by Nandha2Tech — COMMENTED** [review]
Great Work!

**Comment by Nandha2Tech** [comment]
Great Work!

**Review by Nandha2Tech — COMMENTED** [review]
Great Work!

**Review by Nandha2Tech — COMMENTED** [review]
Great Work!

**Review by Nandha2Tech — COMMENTED** [review]
Great Work!

**Comment by Nandha2Tech** [comment]
Great Work!

**Pull request closed without merging**
